#!/bin/bash -e
# generic preseeding of inithooks.conf if it doesn't exist

[ -e $INITHOOKS_CONF ] && exit 0

MASTERPASS=$(mcookie | cut --bytes 1-8)

cat>$INITHOOKS_CONF<<EOF
export ROOT_PASS=$MASTERPASS
export DB_PASS=$MASTERPASS
export APP_PASS=$MASTERPASS
export APP_EMAIL=admin@example.com
export APP_DOMAIN=DEFAULT
export HUB_APIKEY=SKIP
export SEC_ALERTS=SKIP
export SEC_UPDATES=SKIP
export LDAP_BASEDN=DEFAULT
export LDAP_BINDDN="cn=nsspam,dc=example,dc=com"
export LDAP_PASS=$MASTERPASS
export LDAP_SERVER=127.0.0.1
export SAMBA_BINDDN="cn=samba,dc=example,dc=com"
export SAMBA_PASS=$MASTERPASS
EOF

chmod +x /usr/lib/inithooks/firstboot.d/30turnkey-init-fence

